=== chi-university-of-manchester/openCDMS/psygrid-common/etc/schemas/import.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
Copyright (c) 2006-2008, The University of Manchester, UK.

This file is part of PsyGrid.

PsyGrid is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as 
published by the Free Software Foundation, either version 3 of 
the License, or (at your option) any later version.

PsyGrid is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public 
License along with PsyGrid.  If not, see <http://www.gnu.org/licenses/>.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="import">
        <xs:complexType>
            <xs:sequence>
            	<xs:element name="projectDirectory" type="xs:string" minOccurs="0" maxOccurs="1"/>
            	<xs:element name="sources" type="sourcestype" />
        		<xs:element name="group" type="grouptype" minOccurs="0" maxOccurs="1"/>
        		<xs:element name="consentformgroups" type="consentformgroupstype" minOccurs="1" maxOccurs="1"/>
        		<xs:element name="schedulestartdate" type="schedulestartdatetype" minOccurs="0" maxOccurs="1"/>
        		<xs:element name="skiprows" type="skiprowstype" minOccurs="0" maxOccurs="1"/>
            	<xs:element name="users" type="userstype" minOccurs="0" maxOccurs="1"/>
            	<xs:element name="documents" type="documentstype" minOccurs="1" maxOccurs="1"/>
				<xs:element name="translations"  type="translationstype" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        	<xs:attribute name="project" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="sourcestype">
        <xs:sequence>
            <xs:element name="csvsource" type="csvsourcetype" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="jdbcsource" type="jdbcsourcetype" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="sourcetype">
    	<xs:sequence>
        	<xs:element name="id" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1"/>
        	<xs:element name="primary" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
            <xs:element name="identifiercolumn" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
            <xs:element name="identifierclass" type="xs:string" minOccurs="0" maxOccurs="1"/>
       	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="csvsourcetype">
        <xs:complexContent>
            <xs:extension base="sourcetype">
            	<xs:sequence>
                	<xs:element name="filename" type="xs:string" minOccurs="1" maxOccurs="1"/>
                	<xs:element name="headerrows" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1"/>
               	</xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="jdbcsourcetype">
        <xs:complexContent>
            <xs:extension base="sourcetype">
            	<xs:sequence>
                	<xs:element name="url" type="xs:string" minOccurs="1" maxOccurs="1"/>
                	<xs:element name="username" type="xs:string" minOccurs="1" maxOccurs="1"/>
                	<xs:element name="password" type="xs:string" minOccurs="1" maxOccurs="1"/>
                	<xs:element name="query" type="xs:string" minOccurs="1" maxOccurs="1"/>
               	</xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="grouptype">
    	<xs:sequence>
        	<xs:element name="mapping" type="mappingtype"/>
       	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="consentformgroupstype">
        <xs:sequence>
        	<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="consentformgroup" type="consentformgrouptype" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="consentformgrouptype">
        <xs:sequence>
        	<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="primaryconsentform" type="primaryconsentformtype" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
		<xs:attribute name="index" type="xs:nonNegativeInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="consentformtype">
    	<xs:sequence>
        	<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
	        <xs:element name="mapping" type="mappingtype" minOccurs="0" maxOccurs="1"/>
	        <xs:element name="constant" type="constanttype" minOccurs="0" maxOccurs="1"/>
       	</xs:sequence>
        <xs:attribute name="index" type="xs:nonNegativeInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="primaryconsentformtype">
        <xs:complexContent>
            <xs:extension base="consentformtype">
            	<xs:sequence>
        			<xs:element name="associatedconsentform" type="consentformtype" minOccurs="0" maxOccurs="unbounded"/>
       			</xs:sequence>
       		</xs:extension>
   		</xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="schedulestartdatetype">
    	<xs:sequence>
    		<xs:element name="format" type="xs:string" minOccurs="1" maxOccurs="1"/>
    		<xs:element name="mapping" type="mappingtype" minOccurs="1" maxOccurs="1"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="skiprowstype">
    	<xs:sequence>
    		<xs:element name="row" type="xs:integer" minOccurs="1" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="userstype">
    	<xs:sequence>
    		<xs:element name="user" type="usertype" minOccurs="1" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="usertype">
    	<xs:sequence>
    		<xs:element name="native" type="xs:string" minOccurs="1" maxOccurs="1"/>
    		<xs:element name="psygrid" type="xs:string" minOccurs="1" maxOccurs="1"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="documentstype">
        <xs:sequence>
            <xs:element name="document" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="translationstype">
    	<xs:sequence>
    		<xs:element name="translation" type="translationtype" minOccurs="1" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="translationtype">
    	<xs:sequence>
    		<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
    		<xs:element name="input" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
    		<xs:element name="output" type="xs:string" minOccurs="1" maxOccurs="1"/>
    	</xs:sequence>
    	<xs:attribute name="standardCode" type="xs:boolean" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="mappingtype">
    	<xs:sequence>
    		<xs:element name="translations" type="translationstype" minOccurs="0" maxOccurs="1"/>
    		<xs:element name="otherText" type="mappingtype" minOccurs="0" maxOccurs="1"/>
   		</xs:sequence>
        <xs:attribute name="source" type="xs:integer" use="required"/>
        <xs:attribute name="default" type="xs:string"/>
        <xs:attribute name="column" type="xs:nonNegativeInteger" use="required"/>
    </xs:complexType>

     <xs:complexType name="constanttype">
    	<xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>
    
</xs:schema>

=== chi-university-of-manchester/openCDMS/import/etc/xml/neden/neden.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
Copyright (c) 2006-2008, The University of Manchester, UK.

This file is part of PsyGrid.

PsyGrid is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as 
published by the Free Software Foundation, either version 3 of 
the License, or (at your option) any later version.

PsyGrid is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public 
License along with PsyGrid.  If not, see <http://www.gnu.org/licenses/>.
-->
<import project="NED" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/lucy/svn/web2/import/etc/schemas/import.xsd">
	<sources>
		<csvsource>
			<id>0</id>
			<primary>true</primary>
			<identifiercolumn>0</identifiercolumn>
			<identifierclass>org.psygrid.dataimport.identifier.NedenParser</identifierclass>
			<filename>Personal_Details_Form.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>1</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_PANSS.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>2</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Insight_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>3</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Calgary_Depression_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
				<csvsource>
			<id>4</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_EQ5D.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>5</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Duration_of_Untreated_Psychosis.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>6</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Global_Assessment_of_Functioning.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>7</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Family_History_-_Relative_One.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>8</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_CSSRI_Sociodemographic_Information.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>9</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_CSSRI_Usual_Living_Situation.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>10</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_CSSRI_Employment_and_Income.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>11</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_CSSRI_Service_Receipt.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>12</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_CSSRI_Medication_Profile.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>13</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_CSSRI_Informal_Care_and_Help.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>14</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Self_Harm_(Client,_Most_Serious).csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>15</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Self_Harm_(Client,_Closest).csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>16</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Self_Harm_(Carer,_Most_Serious).csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>17</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Self_Harm_(Carer,_Closest).csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>18</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Violence_(Client,_Most_Serious).csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>19</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Violence_(Client,_Closest).csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>20</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Violence_(Carer,_Most_Serious).csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>21</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Violence_(Carer,_Closest).csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>22</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Pathways_to_Care_(Collated).csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>23</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Pathways_to_Care_(Pathway_One).csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>24</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Substance_Use.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>25</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Treatment_Documentation_-_Treatment_One.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>26</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Treatment_Documentation_-_Treatment_Two.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>27</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Treatment_Documentation_-_Treatment_Three.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>28</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Premorbid_Adjustment_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>29</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Time_Use_Interview.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>30</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Baseline_Young_Mania_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>31</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Six_Month_Young_Mania_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>32</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Six_Month_PANSS.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>33</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Six_Month_Calgary_Depression_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>34</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Twelve_Month_PANSS.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>35</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Twelve_Month_Calgary_Depression_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>36</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Twelve_Month_Young_Mania_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>37</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Twelve_Month_Insight_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>38</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Twelve_Month_Global_Assessment_of_Functioning.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>39</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Twelve_Month_EQ5D.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>40</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Six_Month_Service_Engagment_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>41</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Twelve_Month_Service_Engagment_Scale.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>42</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Six_Month_Self_Harm.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
			<id>43</id>
			<primary>false</primary>
			<identifiercolumn>0</identifiercolumn>
			<filename>Six_Month_Violence.csv</filename>
			<headerrows>6</headerrows>
		</csvsource>
		<csvsource>
